# Generated by Django 5.0.2 on 2024-03-09 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=200, verbose_name='スレッドのタイトル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スレッド',
                'verbose_name_plural': 'スレッド',
                'db_table': 'thread',
            },
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('question', models.CharField(max_length=2000, verbose_name='ユーザーからの質問')),
                ('answer', models.CharField(max_length=2000, null=True, verbose_name='AIからの回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_and_answer', to='ai_talk.thread')),
            ],
            options={
                'verbose_name': '質問と回答',
                'verbose_name_plural': '質問と回答',
                'db_table': 'question',
            },
        ),
    ]
